name: CI Tests

on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        gemfile: [ sidekiq6, sidekiq7 ]
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/Gemfile-${{ matrix.gemfile }}

    services:
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Run tests
        run: bundle exec bin/test
      
